### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [ole/Ampere#7]
I'd be cool to also add CocoaPods support. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by ole** [comment]
Thanks for the suggestion, I'll think about it. I deliberately haven't done anything for CocoaPods or Carthage support yet, mainly because I'm not looking forward to having to make a formal release for every little change. But that's probably not the right way to think about this.

(I haven't tried, but I think the library should work with Carthage out of the box since it has no dependencies.)

**Comment by lfarah** [comment]
I could help you to push to CocoaPods every time you send a change.
When I brought my libs to CocoaPods, I became way more organized on Git. I feel like I learned a lot.

Also, CocoaPods gives us at [AwesomeiOS](https://github.com/vsouza/awesome-ios) a library quality index, which helps us filter libraries

**Comment by ole** [comment]
Note to self: CocoaPods requires a `.swift-version` file in the directory for Swift 3 support. See https://github.com/CocoaPods/blog.cocoapods.org/pull/135/files.

**Comment by ole** [comment]
I'm closing this because I don't want to add a Cocoapods spec. With SwiftPM support coming in Xcode 11, I'd rather move the entire project over to SwiftPM and move away from Xcode project files completely. Sorry.
